baseurl = "http://olivierguillet.com/"
languageCode = "en-us"
title = "Olivier Guillet | Cyberculture"
theme = "hugo-steam-theme"
disqusShortname = "Olivier Guillet"
paginate = 10

[permalinks]
    post = "/:year/:month/:filename/"
    about = "/:filename/"

[params]

	title = "Olivier Guillet"
	subtitle = "Cyberculture"
	copyright = "All rights reserved."

	# You can choose between green, orange, red and blue.
	themeColor = "blue"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = "UA-27460975-1"

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Olivier Guillet"
	bio = ""
	description = "Cyberculture"
	location = "Nantes - France" # optional
	twitter = "OlivierGuillet" # optional
	github = "OlivierGuillet" # optional

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs. 
	comments = "disqus"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"